### ISSUE TITLE
Audio starts jittering the more sounds are played

### ISSUE THREAD

**Issue by cybersoulK** [orottier/web-audio-api-rs#396] opened 2023-11-21 10:48 UTC
after a few hundred source nodes connect and disconnect, there are a lot of loud pops or sound jitter. / abrupt interruptions (some leak in web-audio-api or cpal usage?)

[pop.mp3.zip](https://github.com/orottier/web-audio-api-rs/files/13377884/pop.mp3.zip) (internal recording of the bullets sounds, 

- Cpal backend is used
- Web equivalent does well
- One buffer per source node. (Cloned)
- A Node graph is created (and later disconnected) per sound: Source -> gain -> destination
- None of these nodes are connected with anything else.
- This issues happens on both Mac and windows

Render capacity shows increasing numbers:
<img width="1069" alt="Screenshot 2023-11-21 at 2 41 38 AM" src="https://github.com/orottier/web-audio-api-rs/assets/102260392/39d2beb1-e424-4d0d-b6ea-1d630f3a66b3">
<img width="1088" alt="Screenshot 2023-11-21 at 2 39 54 AM" src="https://github.com/orottier/web-audio-api-rs/assets/102260392/8c0a850d-9962-4454-8c59-4f547b0c195e">
<img width="1104" alt="Screenshot 2023-11-21 at 2 41 01 AM" src="https://github.com/orottier/web-audio-api-rs/assets/102260392/af8df810-35bf-459e-9a37-5cda4c664560">

I used kira.rs with the cpal backend, and it never did this.
I just compared them side by side with exact same sound conditions.

My minimal code for each sound that plays:
```rust
 let options = AudioBufferSourceOptions::default();
 let mut source_node = AudioBufferSourceNode::new(context, options);
source_node.set_buffer(buffer);

let mut options = GainOptions::default();
options.gain = volume;
let gain_node = GainNode::new(context, options);

source_node.connect(&gain_node);
gain_node.connect(&context.destination());

source_node.start();

Sound {
   source_node,
   gain_node,
}
```
and later when the sound stops:
```rust
impl Drop for Sound {
   self.source_node.disconnect();
   self.gain_node.disconnect();
}
```

I made sure that all of the sounds are being dropped and their nodes disconnected

**Comment by orottier** [comment] 2023-11-21 18:31
Thanks for the detailed report.
I can confirm on my machine that we run into max load with about 500 sounds buffersourcenodes+gain concurrently and adding 10 nodes in bursts every 5 milliseconds.
I captured a profile which indicates we spend about 75% of the CPU ordering the audio graph, so that is definitely the area to look for improvements.
FYI From other benchmarks we know that for static audio graphs we are about a factor 2 slower than the browser implementations.
<img width="1060" alt="Schermafbeelding 2023-11-21 om 19 26 48" src="https://github.com/orottier/web-audio-api-rs/assets/5442615/a9dae2ed-02f6-49c3-b152-0f05e72132b0">

**Comment by cybersoulK** [comment] 2023-11-21 20:03
but i don't have 500 nodes connected at a given time,
i have only 5 sounds playing maximum at a time.

Everything should be disconnected and cleared, something is leaking, that's making the cpu unusable...

**Comment by orottier** [comment] 2023-11-22 08:11
Right, I misunderstood.

Changing my stress test to run less nodes concurrently but checking the load for a longer running time, I can't seem to reproduce this issue.

Are you sure the `Drop` method is called? Or are you holding on to the Sounds for a very long time?

In the current implementation, we don't free up audio processor resources when the control thread still holds on to the corresponding AudioNode. I believe @b-ma already mentioned that we should not do this in case the node has ended/stopped and cannot be started again but this is not implemented yet: #397 

Tangentially, we should probably add an `AudioContext::print_diagnostics` to aid debugging in these cases. It should print some counters and the full audio graph

**Comment by b-ma** [comment] 2023-11-22 08:46
The only difference I can imagine is the size of the `AudioBuffer` (even if I don't really get why it would change anything), but just in case, could you tell us more about your audio buffer (sample rate, duration, etc.)?

**Comment by b-ma** [comment] 2023-11-23 07:15
Just another question, is your source looping?

**Comment by cybersoulK** [comment] 2023-11-23 07:25
> Just another question, is your source looping?

I have some looping, but they only play 20 times. The ones that play hundreds of times are not looping and are less than 0.5 seconds in duration.

**Comment by b-ma** [comment] 2023-11-24 13:53
Does it helps if you `stop()` the node before `disconnect()`?

```rs
impl Drop for Sound {
   self.source_node.stop();
   // this is not mandatory then, but doesn't hurt 
   self.source_node.disconnect();
   self.gain_node.disconnect();
}
```

**Comment by cybersoulK** [comment] 2023-11-24 15:14
using stop doesn't fix the issue.
it's odd that you were not able to replicate this issue yet.
 i will try to make a minimal example

**Comment by cybersoulK** [comment] 2023-11-24 17:29
https://github.com/cybersoulK/debug_web_audio_api
i made a minimal example, can you check if after 1 minute the audio breaks?

**Comment by b-ma** [comment] 2023-11-24 18:23
Hey, thanks for the example,  I think I managed to make it work by just doing:

```rs
impl Drop for Sound {
    fn drop(&mut self) {
        // self.source_node.disconnect();
        // self.gain_node.disconnect();
    }
}
```

But I have no idea of the why, this is a bit problematic...  If I leave any of the `disconnect` methods, then at some point your `active_sounds` list starts to grow indefinitely, just like if the `onened` callback was not called, @orottier any idea?

Just asking myself and maybe this is because we have only part of the code, but I don't understand why you keep this list of active nodes? You could just spawn them and forget them right away

**Comment by orottier** [comment] 2023-11-24 18:32
Hah, now this is interesting.

It's a manifestation of the bug I just fixed in https://github.com/orottier/web-audio-api-rs/pull/400/commits/7b048c2f60a750543c8d8ecdef7910ce6686aee0
This fix is not present in v0.36.1

The fix addresses the issue that `disconnect` disassociates the nodes from its audio params. Dynamic lifetime kicks in for the AudioBufferSourceNode which is freed, but because the AudioParams have tail time `true`, they are never decommissioned.

I haven't tested it yet but I'm convinced this issue does not occur on the `main` branch now.

> Just asking myself and maybe this is because we have only part of the code, but I don't understand why you keep this list of active nodes? You could just spawn them and forget them right away

Indeed. The Web Audio API deals with this for you via dynamic lifetimes, search "fire and forget" on https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode
Meaning, just call `start()` and perhaps call `stop(time)` on it and then just drop the node. The library will free up the resources when the sound is done playing.

**Comment by cybersoulK** [comment] 2023-11-24 18:59
i confirm that the current master solved the issue

**Comment by orottier** [comment] 2023-11-24 19:35
Great to hear! Thanks to your bug report we fixed a logic bug and a performance issue. And we're prepping up a method to better aid users in submitting diagnostics via #401 

I will publish a new release of the library this weekend.

**Closed by orottier** 2023-11-24 19:35 UTC
Labels: Performance
